### ISSUE TITLE
CT Build failed with status code 1:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/sound-waves#26]
```
sound-waves : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 26383ms
Building runnable repository (sound-waves, brands: phet)
Building brand: phet
>> Webpack build complete: 5969ms
>> Unused string: key=singleSource.help.listener, value=Listener can be moved left and right
>> Unused string: key=measure.help.stick, value=Use meter stick to measure waves
>> Unused string: key=measure.help.blueLines, value=Blue lines can be moved left and right to help mark measurement points on waves
>> Unused string: key=twoSource.help.upperSpeaker, value=Upper speaker can be moved up and down
>> Unused string: key=twoSource.help.listener, value=Listener can be moved in all directions
>> Unused string: key=airDensityControlPanel.removeAir, value=Remove Air from Box
>> Unused string: key=airDensityControlPanel.addAir, value=Add Air to Box
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: missing entry for sim title, key = SOUND_WAVES/sound-waves.title
at module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/chipper/js/grunt/buildRunnable.js:157:3)
at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/chipper/js/grunt/Gruntfile.js:298:15
at Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/perennial-alias/js/common/phetTimingLog.js:133:20)
at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/chipper/js/grunt/Gruntfile.js:297:13
at Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/perennial-alias/js/common/phetTimingLog.js:133:20)
at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/chipper/js/grunt/Gruntfile.js:225:7
at wrap (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1692628041596/chipper/js/grunt/Gruntfile.js:69:7)

Full Error details:
AssertionError [ERR_ASSERTION]: missing entry for sim title, key = SOUND_WAVES/sound-waves.title
Snapshot from 8/21/2023, 8:27:21 AM
```

**Comment by matthew-blackman** [comment]
This should be fixed now. Marking as ready for review.
